


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  type-aliases-package: com.example.mapper.UserMapper
server:
  port: 80
